### ISSUE TITLE
[✨ Feat] Exhibiton 페이지 1차 수정

### ISSUE THREAD

**Issue by a40418a** [kapa-kwu-photo-clup/47th-web#18]
# ✨Feature Issue
exhibition 페이지를 수정해보아요

## Description
- 모바일 상에서 오류나는 부분 수정(width 지정, 아래에 안 보이는 부분)
- 모바일 상 hover 삭제
- lazy 기능 추가
- 이미지 이동 기능 추가

## To-do
- [x] lazy 기능 추가
- [x] 모바일 exhibiton 디자인 수정
- [x] 화살표클릭시 모달간 이미지 이동 기능 추가
