### ISSUE TITLE
[✨ Feat] 1차 마무리

### ISSUE THREAD

**Issue by jamooooong** [kapa-kwu-photo-clup/47th-web#25]
# ✨Feature Issue
각 페이지별 mvp를 만족하도록 만들어 배포해도 무리 없을 모습으로 수정을 합니다.

## Description
상단 마진 값 변경
굿즈 달력이미지 추가
글자 여백 및 크기 조절 (시뮬레이터 돌리면서 즉석에서 수정 예정)

## To-do
- [x] 상단 마진 값 조절
- [x] 굿즈페이지 달력 이미지 추가
- [x] /exhibition css
- [ ] 글자 여백 및 크기 조절
- [ ] seo
