### ISSUE TITLE
[✨ Feat] exhibition 페이지 구현

### ISSUE THREAD

**Issue by a40418a** [kapa-kwu-photo-clup/47th-web#8]
# ✨Feature Issue
exhibition 페이지를 만들어요

## Description
봄/여름/가을/겨울 별로 페이지를 나눠 구현
사진 클릭시 상세모달창으로 구현
페이지별로 버튼 hover시 색상 계절에 맞게 다르게 구현

## To-do
- [x] 계절별로 페이지 구현
- [x] 사진 클릭시 상세 모달 창 띄우기
- [x] 계절에 맞게 색상 변경(창닫기, 방향전환, 기수)

## ETC

![Uploading spring.jpg…]()
